### ISSUE TITLE
On-screen messages related to settings are not modified

### ISSUE THREAD

**Issue by c30zD** [sergiomb2/pinball#15]
As I explain in #14, even though it provides a fix for the main issue (messages were originally hard-coded), there is another that remains. The steps to reproduce are as follows:

1. After loading any table, start the game
2. When the "press [key] to launch ball" message is displayed, return to the main menu (make sure the message doesn't disappear _before_ returning to the menu)
3. Change the key to launch the ball
4. Return to the game. The message isn't modified

The same happens if instead of the "launch" message, it is the "reset" message. Nevertheless, the key bindings will work, even though the message suggests otherwise.

I'm opening this issue just so it's somewhere easily accessible, in case anyone wishes to provide a fix.

**Comment by sergiomb2** [comment]
fixed with https://github.com/sergiomb2/pinball/pull/14

**Comment by c30zD** [comment]
Perhaps I didn't explain myself properly. The current issue should be reopened, because it isn't fixed. This issue is about the following two scenarios:

1. The user starts a new game (table is already loaded) and the message to launch the ball appears. Immediately, the user goes back to the main menu and then changes the key in the configuration menu. Then the user returns to the game and sees that the message is still the same.
2. The user finishes the game and the message to restart appears. At this point, the user goes back to the main menu and changes the reset key in the configuration menu. When he comes back, the message is still the same.

What was fixed in #14 was that the reset key and messages are not hard-coded anymore. Therefore, the next time the user starts/ends a game, the message will be correct.

Now, the current issue might never be seen by other people because it is unlikely that the user will stop the game just to change a setting like that, but as the issue is there, I believe it should be tracked somehow. This is why I purpose to reopen the issue.
