### ISSUE TITLE
Pinball exits when loading tables -  undefined symbol: _ZN8BehaviorC2Ev

### ISSUE THREAD

**Issue by orbea** [sergiomb2/pinball#22]
OS: `Slackware64-current`
pinball: f525c0037368e114b024b67d51280c477c681d87

When using pinball built from this repo or from https://github.com/rzr/pinball pinball will exit when trying to load any table.
```
pinball: symbol lookup error: /usr/lib64/pinball/libModuleTux.so.0: undefined symbol: _ZN8BehaviorC2Ev
```
This did not occur with the old pinball-0.3.1 release.

**Comment by orbea** [comment]
This only happens when built with slibtool and not with GNU libtool. Libtool likes to hide and ignore bugs so this could easily be an issue in pinball. I'll try to find out more later.

https://git.midipix.org/cgit.cgi/slibtool/

**Comment by orbea** [comment]
Here are some build logs in case they offer clues.

dlibtool - https://paste.ee/p/7Ra0g
libtool - https://paste.ee/p/LUWol

**Comment by orbea** [comment]
Here are some build logs in case they offer clues.

dlibtool - https://paste.ee/p/7Ra0g
libtool - https://paste.ee/p/LUWol

**Comment by sergiomb2** [comment]
yeah , I have a dejavu , so your pull request  https://github.com/sergiomb2/pinball/pull/23 , have this issue ?

**Comment by orbea** [comment]
No, that PR and this issue are unrelated. This appears to be a change or regression in the slibtool git master. Their latest stable is unaffected.
```
9160500b62fca721ace9df94d440d9e71d587a35 is the first bad commit
commit 9160500b62fca721ace9df94d440d9e71d587a35
Author: midipix <writeonce@midipix.org>
Date:   Mon Mar 5 17:33:21 2018 -0500

    driver: support -export-dynamic (currently as a no-op).

:040000 040000 16440867ffc5aa7904d6b7b51997fb0f94d6f241 3923567a87bb61c241069dc6dd4a7ffe6642a789 M	include
:040000 040000 6267e833c14ee91b215d59126456a51221159bde 4ebc2a5da5bd508273e93d2ff4f6ff8c7191250e M	src
```
I suggest leaving this open and hopefully midipix will be able to fix this soon. I'll update soon.

Alternatively there might be additional reasons to not use `-export-dynamic`?

**Comment by sergiomb2** [comment]
googling by: _ZN8BehaviorC2Ev [1] have 2 results and they are about pinball, so is not a coincidence , I guess . 
slibtool is a replacement of libtool ? in Fedora we use  http://git.savannah.gnu.org/cgit/libtool.git .

https://www.google.pt/search?q=_ZN8BehaviorC2Ev&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&ei=uq_GWsvAPMT38Af64peoAQ

**Comment by orbea** [comment]
Yes, slibtool is a replacement of GNU libtool, it has a lot of good qualities, but I'm not sure its ready for any major distro to switch to it full time yet. I am using it as a personal choice to help find issues in it and in other programs so that it can become more mature. It also has a good way of finding bugs in programs which libtool just outright ignores and hides, but I'm not sure this is such a case.

The README at the midipix github mirror gives a good introduction.
https://github.com/midipix-project/slibtool

**Comment by orbea** [comment]
This has been fixed in slibtool, I'll close this issue now.

https://git.midipix.org/cgit.cgi/slibtool/commit/?id=f5983e8071d8b87b6f14c64f3f8564e934f49d7b

**Comment by sergiomb2** [comment]
thanks , slibtool still have a few users [1] and none rpm 

[1] https://repology.org/metapackage/slibtool/versions

**Comment by orbea** [comment]
I talked to a fedora maintainer today who is in the slibtool irc channel (#midipix) and he said he's stretched too thin to take that up now. I do agree it would be cool to have fedora and/or other rpm distros interested in and testing slibtool too. :)

The thing that slibtool needs most now is testing, the recent release the other day fixed several issues, but there are surely more out there.

As far as pinball is concerned, it would be good to change the table loading logic to not require the libtool archive (`.la`) files. By default slibtool will not install them and this is obviously not compatible with pinball. It can be worked around by using clibtool (symlink to slibtool) which will install the `.la` files for compatibility reasons.

**Comment by sergiomb2** [comment]
> As far as pinball is concerned, it would be good to change the table loading logic to not require the libtool archive (.la) files. 

how we can do that ? have any patch to exemplify

**Comment by orbea** [comment]
The problem appears to be in `src/LoaderModule.cpp`, for example.

https://github.com/sergiomb2/pinball/blob/f525c0037368e114b024b67d51280c477c681d87/src/LoaderModule.cpp#L48

I tried to change it, but my c/c++ knowledge and experience is limited and I didn't get very far..

**Comment by sergiomb2** [comment]
Thanks for the tip , your tip took me here [1]  , I may try revert this patch ,because  port to not-linux is not supported anymore .  I just ask you patience because I may take some months to have time to look at it .

[1]
https://github.com/sergiomb2/pinball/commit/9e1fec09911ede56d46455d43f6c1b01431a82d4
